### ISSUE TITLE
Error when using with SkBee

### ISSUE THREAD

**Issue by LedSzef** [Ekpoa/PoaSkRewritev2#17]
I'm not sure if this is an issue with the SkBee or PoaSK. When I try to use the `register shapeless recipe` section of the SkBee addon (specifically the effect `add %itemstack/recipechoice% to ingredients`), an error appears. After uninstalling the PoaSK addon, the error no longer occurs, and everything works fine.

Skript version: 2.9.2
PoaSK: 4.8.0
SkBee: 3.6.1

```
08.09 14:56:26 [Server] ERROR #!#!
08.09 14:56:26 [Server] ERROR #!#! [Skript] Severe Error:
08.09 14:56:26 [Server] ERROR #!#!
08.09 14:56:26 [Server] ERROR #!#! Something went horribly wrong with Skript.
08.09 14:56:26 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
08.09 14:56:26 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
08.09 14:56:26 [Server] ERROR #!#! Following plugins are probably related to this error in some way:
08.09 14:56:26 [Server] ERROR #!#! SkBee (https://github.com/ShaneBeee/SkBee)
08.09 14:56:26 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
08.09 14:56:26 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
08.09 14:56:26 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
08.09 14:56:26 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
08.09 14:56:26 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
08.09 14:56:26 [Server] ERROR #!#!
08.09 14:56:26 [Server] ERROR #!#! Stack trace:
08.09 14:56:26 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:142)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:172)
08.09 14:56:26 [Server] ERROR #!#! at PoaSK (2).jar//poa.poaskrewritev2.effects.EffRawMetadata.execute(EffRawMetadata.java:53)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
08.09 14:56:26 [Server] ERROR #!#! at SkBee-3.6.1.jar//com.shanebeestudios.skbee.elements.recipe.sections.SecRecipeShapeless.execute(SecRecipeShapeless.java:161)
08.09 14:56:26 [Server] ERROR #!#! at SkBee-3.6.1.jar//com.shanebeestudios.skbee.elements.recipe.sections.SecRecipeShapeless.walk(SecRecipeShapeless.java:124)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
08.09 14:56:26 [Server] ERROR #!#! at Skript-2.9.2.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
08.09 14:56:26 [Server] ERROR #!#! at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
08.09 14:56:26 [Server] ERROR #!#! at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
08.09 14:56:26 [Server] ERROR #!#! at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
08.09 14:56:26 [Server] ERROR #!#! at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
```

**Comment by GentlemanCheesy** [comment]
Would like to note that this issue occurred after installing this addon in the same context of the shapeless recipes system in skbee for me.
