### ISSUE TITLE
spawn fake player [Skript] Severe Error: An error occurred while trying to load a Structure.

### ISSUE THREAD

**Issue by czychuuu** [Ekpoa/PoaSkRewritev2#3]
after the fix of hostname i get this error
befere updating everything was fine

[15:23:26 INFO]: [Skript] Reloading test.sk...
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! [Skript] Severe Error:
[15:23:27 ERROR]: #!#! An error occurred while trying to load a Structure.
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[15:23:27 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[15:23:27 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Stack trace:
[15:23:27 ERROR]: #!#! ch.njol.skript.SkriptAPIException: The class 'boolean' does not provide a default expression. Either allow null (with %-boolean%) or make it mandatory [pattern: spawn fake player named %string% [with skin named %string%] [with name hidden %boolean%] [on tablist %-boolean%] [with latency %-number%] at %location% for %players%]
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.getDefaultExpression(SkriptParser.java:280)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:65)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:967)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.loadCode(Section.java:89)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:237)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:68)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:260)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:178)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:211)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:177)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.loadCode(Section.java:89)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.loadOptionalCode(Section.java:166)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecWhile.init(SecWhile.java:88)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:68)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:260)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:178)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:211)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:177)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:144)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.structures.StructEvent.load(StructEvent.java:85)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:570)
[15:23:27 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
[15:23:27 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:561)
[15:23:27 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[15:23:27 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[15:23:27 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[15:23:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[15:23:27 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:23:27 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[15:23:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013)
[15:23:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998)
[15:23:27 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:541)
[15:23:27 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[15:23:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1558)
[15:23:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[15:23:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:23:27 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Version Information:
[15:23:27 ERROR]: #!#!   Skript: 2.9.0-beta1 (OUTDATED)
[15:23:27 ERROR]: #!#!     Flavor: skriptlang-github
[15:23:27 ERROR]: #!#!     Date: 13:09:23.331556300
[15:23:27 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[15:23:27 ERROR]: #!#!   Minecraft: 1.20.4
[15:23:27 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[15:23:27 ERROR]: #!#!   OS: Linux aarch64 6.5.0-1023-oracle
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Server platform: Paper
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Current node: spawn fake player named "test test" with skin named "steve" on tablist false with latency 0 at location 1 up and 4 in front of player for player (test.sk, line 18)
[15:23:27 ERROR]: #!#! Current item: null
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Thread: Server thread
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! Language: english
[15:23:27 ERROR]: #!#! Link parse mode: DISABLED
[15:23:27 ERROR]: #!#! 
[15:23:27 ERROR]: #!#! End of Error.
[15:23:27 ERROR]: #!#! 
[15:23:27 INFO]: [Skript] Successfully reloaded test.sk. (1234ms)

**Comment by Ekpoa** [comment]
Fixed in latest version
